### ISSUE TITLE
No module named 'numpy'

### ISSUE THREAD

**Issue by OlSnubbo** [Surasia/InfiniteRippingGuide#1]
![2022-12-11](https://user-images.githubusercontent.com/120334453/206923369-118b0ce4-7122-448a-98fa-04e430b63891.png)
![2022-12-11 (2)](https://user-images.githubusercontent.com/120334453/206923371-483b025e-faaa-4da0-a7c0-331e00085407.png)
I'm unsure if I missed a step in the guide or if I somehow broke something? Tried running the unpacker after putting in the file paths for the unpack and deploy path. However every time I tried running it just keeps popping out this message, thought maybe it's supposed to say it so I left it alone for a few minutes. After returning I saw it still said that so I tried doing it again and same message.

I have barely any knowledge when it comes to coding or python but from what I can guess from what it's saying its trying to import something named numpy but such thing doesn't exist? I'm guessing I'm wrong on that guess though since again I have very little experience when it comes to this sort of thing.

**Comment by Surasia** [comment]
Open a command prompt and type "pip install numpy"
